### ISSUE TITLE
Tegra TX1 build?

### ISSUE THREAD

**Issue by rbiasini** [krumboeck/usb2can#7]
Does this build on NVidia Tegra TX1?

Thanks!

**Comment by krumboeck** [comment]
I can't say it for sure, because I don't have access to this piece of hardware.

But as far I can see, the latest kernel version for Jetson TX1 is 3.10.96. Maybe it works out of the box, because the driver is part of the mainline kernel since 3.9.

If not, you have to check if CAN support is enabled:
* Kernel with CAN support: Simple compile and install the driver from this page
* Kernel without CAN support: Recompile the kernel with CAN support and USB2CAN module enabled

Does this answer your question?

**Comment by rbiasini** [comment]
It helps for sure. Thanks!
I should have access to NVidia TX1 soon, will let you know.
