### ISSUE TITLE
Sending Can messages (periodic and spontaneous )

### ISSUE THREAD

**Issue by IslamHelmy** [krumboeck/usb2can#8]
Hi , 

* I just have got the following [USB2CAN](http://www.8devices.com/products/usb2can) and now i am bringing it up (on ubuntu 14.04 LTS , using kernel 3.13.0-115-generic).
* When i have read the user guide [usb2can user guide](http://www.8devices.com/media/products/usb2can/downloads/usb2can_user_guide.pdf) i couldn't find something which is related to sending can messages cyclically or spontaneous with specific cycle time and identifying the can message ID.

* The status that i am now able to communicate with USB2CAN adapter run the following command cansend can0 01010101#0102030405060708 , and the status led is blinking with green light which is suppose means that i have send the data correctly.

so what i need to be able to do is:
1. To send 5 can message with cycle time 2,3,4,5,and 6 msec respectively , with can message IDs 0x101,0x102,0x103,0x104,and 0x105
2. send can message spontaneous , i.e just one time sent based on specific event
3. How to stop the transmission of specific can message.
4. How to test sending and receiving the can data itself ?
 
could you please help me to answer these questions ?

**Comment by krumboeck** [comment]
Hi!


I don't know which type of answers you expect, because I don't know your skills and environment.

You can find informations about SocketCAN programming here:
https://en.wikipedia.org/wiki/SocketCAN
https://www.kernel.org/doc/Documentation/networking/can.txt


Answers to your questions:
1. Write a program in any language which supports at least network programming (some of them already has specific bindings for SocketCAN). If you search for a solution on the command line, maybe canplayer (from can-utils) can do this.
2. Same answer, but with cansend.
3. Depends on your program. Solution for command line: Separate the cyclic messages to different processes, so you can kill the process to stop sending.
4. You can use loop (and silent) mode: ip link set can0 type can help

regards,
Bernd



Am 2017-04-28 um 13:26 schrieb IslamHelmy:
